apiVersion: apps/v1
kind: Deployment
metadata:
  name: c8-perftest
  namespace: camunda-perf
  labels:
    app: c8-perftest
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: c8-perftest
  template:
    metadata:
      labels:
        app: c8-perftest
    spec:
      containers:
      - name: c8-perftest
        image: 218175819274.dkr.ecr.eu-central-1.amazonaws.com/c8-perftest:latest
        env:
          - name: SPRING_APPLICATION_JSON
            valueFrom:
              configMapKeyRef:
                name: c8-perftest-config
                key: spring-config.json
---
apiVersion: v1
kind: Service
metadata:
  name: c8-perftest-gateway
  namespace: camunda-perf
  labels:
    app: c8-perftest
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: c8-perftest