apiVersion: v1
kind: ConfigMap
metadata:
  name: c8-perftest-config
  namespace: camunda-perf
data:
  spring-config.json:
    '{
      "zeebe.client.broker.gateway-address": "camunda8-zeebe-gateway:26500",
      "zeebe.client.security.plaintext": "true",
      "zeebe.client.worker.max-jobs-active": "16",
      "zeebe.client.worker.threads": "32",
      "workerSleepTime": "200"
     }'